### ISSUE TITLE
Failed to start the jersey container

### ISSUE THREAD

**Issue by alittlebrighter** [ef-labs/vertx-jersey#51]
I'm trying to run the jersey server in an embedded vertx application.  I copied code from here: https://github.com/ef-labs/vertx-jersey/tree/develop/examples/maven-simplest

and when I try to run the application I'm getting the following error:
```
SEVERE: Failed to start the jersey container
java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:327)
	at com.englishtown.vertx.jersey.impl.DefaultVertxContainer.getApplicationHandlerDelegate(DefaultVertxContainer.java:101)
	at com.englishtown.vertx.jersey.impl.DefaultVertxContainer.getApplicationHandler(DefaultVertxContainer.java:126)
	at com.englishtown.vertx.jersey.impl.DefaultVertxContainer.start(DefaultVertxContainer.java:49)
	at com.englishtown.vertx.jersey.impl.DefaultJerseyServer.lambda$start$0(DefaultJerseyServer.java:94)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:303)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Here are the dependencies I've declared in my build.gradle: 
```
def vertxVersion = "3.3.3"
def vertxJerseyVersion = "4.5.1"

dependencies {
    compile "javax.ws.rs:javax.ws.rs:1.+"

    compile "io.vertx:vertx-core:$vertxVersion"
    compile "io.vertx:vertx-web:$vertxVersion"

    compile "com.englishtown.vertx:vertx-jersey:$vertxJerseyVersion"
    compile "com.englishtown.vertx:vertx-hk2:2.4.0"
}
```
I'm sure I'm just missing something obvious so any help would be appreciated.

**Comment by alittlebrighter** [comment]
The issue was the javax.ws.rs dependency
