### ISSUE TITLE
Jackson incompatibility in clustered mode

### ISSUE THREAD

**Issue by axlider** [ef-labs/vertx-jersey#55]
When i run a server in clustered mode with Hazlecast, i get this exception. Obviously the vertx-jersey-jackson dependencies are not compatible with Hazlecast dependencies.

Name of the hazelcast schema location incorrect using default 
[LOCAL] [dev] [3.6.3] Interfaces is enabled, trying to pick one address matching to one of: [127.0.0.1] 
[LOCAL] [dev] [3.6.3] Picked Address[127.0.0.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true 
[127.0.0.1]:5701 [dev] [3.6.3] Hazelcast 3.6.3 (20160527 - 08b28c3) starting at Address[127.0.0.1]:5701 
[127.0.0.1]:5701 [dev] [3.6.3] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved. 
[127.0.0.1]:5701 [dev] [3.6.3] Configured Hazelcast Serialization version : 1 
[127.0.0.1]:5701 [dev] [3.6.3] Backpressure is disabled 
[127.0.0.1]:5701 [dev] [3.6.3] Starting with 2 generic operation threads and 4 partition operation threads. 
[127.0.0.1]:5701 [dev] [3.6.3] Creating TcpIpJoiner 
[127.0.0.1]:5701 [dev] [3.6.3] Address[127.0.0.1]:5701 is STARTING 
[127.0.0.1]:5701 [dev] [3.6.3] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads 
[127.0.0.1]:5701 [dev] [3.6.3] Connecting to /127.0.0.1:5703, timeout: 0, bind-any: true 
[127.0.0.1]:5701 [dev] [3.6.3] Connecting to /127.0.0.1:5702, timeout: 0, bind-any: true 
[127.0.0.1]:5701 [dev] [3.6.3] Could not connect to: /127.0.0.1:5702. Reason: SocketException[Connection refused: connect to address /127.0.0.1:5702] 
[127.0.0.1]:5701 [dev] [3.6.3] Address[127.0.0.1]:5702 is added to the blacklist. 
[127.0.0.1]:5701 [dev] [3.6.3] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused: connect to address /127.0.0.1:5703] 
[127.0.0.1]:5701 [dev] [3.6.3] Address[127.0.0.1]:5703 is added to the blacklist. 
[127.0.0.1]:5701 [dev] [3.6.3] 

Members [1] {
	Member [127.0.0.1]:5701 this
}
 
[127.0.0.1]:5701 [dev] [3.6.3] Address[127.0.0.1]:5701 is STARTED 
Unhandled exception 
java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:543)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:460)
	at io.vertx.core.json.Json.<clinit>(Json.java:44)
	at io.vertx.core.json.JsonObject.encode(JsonObject.java:751)
	at io.vertx.core.impl.HAManager.<init>(HAManager.java:147)
	at io.vertx.core.impl.VertxImpl.lambda$new$0(VertxImpl.java:190)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:188)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)

**Comment by adrianluisgonzalez** [comment]
What version of jackson is hazelcast expecting?  I was pretty sure vertx-jersey is using the same version as vert.x.

**Comment by axlider** [comment]
Finally I could fix it. I now have only jackson 2.7.4 on my classpath. 
Before i also had jackson 2.6.1 on my classpath. 
In order to resolve this i removed two dependencies:

```
<dependency>
    <groupId>com.englishtown.vertx</groupId>
    <artifactId>vertx-jersey-jackson</artifactId>
    <version>4.2.0</version>
</dependency>
<dependency>
    <groupId>com.englishtown.vertx</groupId>
    <artifactId>vertx-jersey-swagger</artifactId>
    <version>4.2.0</version>
</dependency>
```

and added dependencies for jersey.media.jackson:

```
<jersey.media.jackson.version>2.22</jersey.media.jackson.version>
<dependency>
		  <groupId>org.glassfish.jersey.media</groupId>
		  <artifactId>jersey-media-json-jackson</artifactId>
		  <version>${jersey.media.jackson.version}</version>
</dependency>

```
and jackson:
<jackson.version>2.7.4</jackson.version>
 
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                <artifactId>jackson-jaxrs-base</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                <artifactId>jackson-jaxrs-json-provider</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-xml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-joda</artifactId>
                <version>${jackson.version}</version>
            </dependency>

But the conflict appeared after I added hazlecast. So propably the conflict was there before but appeard because hazlecast was the first component making a conflicting call between jackson versions (API change between jackson versions):

com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;

BTW: Great work!
One question: Does using jersey in verticles conflict somehow with asyncronous nature of vertx?

**Comment by adrianluisgonzalez** [comment]
Thanks.  

As long as you use the `@Suspended AsyncResponse` (https://jersey.java.net/documentation/latest/async.html) you should be able to use vert.x as usual without blocking event loop threads.  When your async work is complete, just resume the AsyncResponse to write the response.

There are some limitations around dependency injection proxying, but the majority of Jersey features should work.
